version: '3.5'

services:

 crdb:
   image: cockroachdb/cockroach:v19.2.2
   container_name: crdb-1
   ports:
     - "26257:26257"
     - "8080:8080"
   command: start-single-node --insecure
   volumes:
     - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"

 minio:
   image: minio/minio
   container_name: minio
   environment:
     - MINIO_ACCESS_KEY=miniominio
     - MINIO_SECRET_KEY=miniominio13
     - MINIO_REGION_NAME=us-east-1
   ports:
     - "9000:9000"
   command: server /data
   volumes:
     - ${PWD}/data:/data

 nifi:
  image: apache/nifi:1.10.0
  container_name: nifi
  ports:
    - "9090:9090"
  environment:
    - NIFI_WEB_HTTP_PORT=9090
  volumes:
    - ${PWD}/nifi/extensions:/opt/nifi/nifi-current/extensions/
    - ${PWD}/nifi/templates:/opt/nifi/nifi-current/conf/templates/


